
package vilsmeier;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransaktionsService", targetNamespace = "http://service.vilsmeier/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransaktionsService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<vilsmeier.Transaktion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alleTransaktionenAnzeigenFuerKonto", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.AlleTransaktionenAnzeigenFuerKonto")
    @ResponseWrapper(localName = "alleTransaktionenAnzeigenFuerKontoResponse", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.AlleTransaktionenAnzeigenFuerKontoResponse")
    public List<Transaktion> alleTransaktionenAnzeigenFuerKonto(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vilsmeier.Transaktionstyp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transaktionsTypFinden", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionsTypFinden")
    @ResponseWrapper(localName = "transaktionsTypFindenResponse", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionsTypFindenResponse")
    public Transaktionstyp transaktionsTypFinden(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vilsmeier.Transaktion
     * @throws TransaktionFailedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transaktionDurchfuehren", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionDurchfuehren")
    @ResponseWrapper(localName = "transaktionDurchfuehrenResponse", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionDurchfuehrenResponse")
    public Transaktion transaktionDurchfuehren(
        @WebParam(name = "arg0", targetNamespace = "")
        Transaktion arg0)
        throws TransaktionFailedException_Exception
    ;

    /**
     * 
     * @param transaktion
     * @return
     *     returns vilsmeier.Transaktion
     * @throws TransaktionFailedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transaktionTaetigen", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionTaetigen")
    @ResponseWrapper(localName = "transaktionTaetigenResponse", targetNamespace = "http://service.vilsmeier/", className = "vilsmeier.TransaktionTaetigenResponse")
    public Transaktion transaktionTaetigen(
        @WebParam(name = "transaktion", targetNamespace = "")
        Transaktion transaktion)
        throws TransaktionFailedException_Exception
    ;

}
