
package vilsmeier;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TransaktionFailedException", targetNamespace = "http://service.vilsmeier/")
public class TransaktionFailedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TransaktionFailedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TransaktionFailedException_Exception(String message, TransaktionFailedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TransaktionFailedException_Exception(String message, TransaktionFailedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: vilsmeier.TransaktionFailedException
     */
    public TransaktionFailedException getFaultInfo() {
        return faultInfo;
    }

}
